--- #YAML:1.0
name:               Audio-Scan
version:            0.75
abstract:           Fast C metadata and tag reader for all common audio file formats
author:
    - Andy Grundman <andy@slimdevices.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
